name: Dispatch Event on Push

on:
  push:
    branches:
      - master  # 监听master分支的推送事件

jobs:
  dispatch_event:
    runs-on: ubuntu-latest
    
    steps:
      - name: Send Dispatch Event
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token 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" \
          https://api.github.com/repos/MoreChickenDelivered/fff-front-e2e/dispatches \
          -d '{"event_type": "vercel-deploy-success", "client_payload": {"repository": "fff-front-e2e", "branch": "dev"}}'
